# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/talk/out
.PHONY: all
all:
	$(MAKE) -C .. gunit libjingle_unittest_main libjingle_unittest libjingle_sound_unittest libjingle_p2p_unittest libjingle_media_unittest libjingle_peerconnection_unittest
